int zerou=0;
float boss2;
int larg_ult;
int rageon=0;
int cont_rage;
int selecao=0;
int personagem;
int aumenta;
float constant=0;
int hp_boss=100;
float move_personagem;
int fase=1;
int cheat;
int facil,hard;
bool direita=false;
bool esquerda=false;
bool cima=false;
bool baixo=false;
int quant_rage=0;
int rage=0;
bool tiroon=false;
float op_menu=0;
int title=1;
int opcao=1;
int gameover;
float gs,sg;
int largura_personagem=10,largura_boss=10;
float px;
float pp,pp2,pb,pi1,arrow;
GLuint texturapersonagem;
GLuint texturapersonagem2;
GLuint texturafundo;
GLuint texturafundo2;
GLuint texturaboss;
GLuint texturaboss2;
GLuint texturapause;
GLuint texturatiro;
GLuint texturagameover;
GLuint texturatitulo1;
GLuint texturavida;
GLuint texturaselecao;
GLuint texturarrow;
GLuint texturaultimate;
GLuint texturault;
GLuint texturafim;
int quantidadeinimigos1=0,quantidadeinimigos2=0,quantidadeinimigos3=0,quantidadeinimigos4=0;
int acerto;
int mb;
int bos;
int inimigos;
int maxtiros;
int powerup;
int tiros[20];
float xe[5];
float xproj[5],xprojb[100];
int vidas;
int tiro;
int tiroinimigo1;
int tiroinimigo2;
int tiroinimigo3;
int tiroinimigo4;
int tiroboss=0;
int e;
int pis;
int cont;
int caux;
float x[20];
float xo[20];
float z[20],w=0;
float xi;
float yi;
float xtb[100],ytb[100],xtinimigo1[20],xprojinimigo1[20],xtinimigo2[20],xprojinimigo2[20],xtinimigo3[25],xprojinimigo3[25],kprojinimigo3[25],kprojinimigo4[25],xprojinimigo4[25],xtinimigo4[25];
float xinimigo1[5],yinimigo1[5],xinimigo2[5],yinimigo2[5],xinimigo3[5],yinimigo3[5],xinimigo4[5],yinimigo4[5];
int pause=1;
float xb,yb;
int sentidoinimigo1[10],sentidoinimigo2[10];
float sentidoinimigo3[10],sentidoinimigo4[10];
int  quantidade_quadrados,const_quadrados,const_tiro_boss,quantidade_tiro_boss,maximo_inimigo1,maximo_tiro_inimigo1,maximo_inimigo2,maximo_tiro_inimigo2,maximo_inimigo3,maximo_tiro_inimigo3,maximo_inimigo4,maximo_tiro_inimigo4;
float x_ult,y_ult;
void carregar_variaveis()
{
    if(facil==1){
        maximo_inimigo1=5;       maximo_inimigo2 = 5;       maximo_inimigo3 = 5;     maximo_inimigo4 = 5;    const_quadrados = 15;   quantidade_quadrados=5;
        maximo_tiro_inimigo1=10; maximo_tiro_inimigo2 = 10; maximo_tiro_inimigo3=15; maximo_tiro_inimigo4=15;quantidade_tiro_boss=5; const_tiro_boss = 12;
    }
    if(hard==1){
        maximo_inimigo1=10;      maximo_inimigo2 = 10;      maximo_inimigo3 = 10;    maximo_inimigo4 = 10;   const_quadrados = 5;   const_tiro_boss = 5;
        maximo_tiro_inimigo1=20; maximo_tiro_inimigo2 = 20; maximo_tiro_inimigo3=25; maximo_tiro_inimigo4=25;quantidade_tiro_boss=10;quantidade_quadrados=10;
    }
    e=1;
    pis=1;
    cont=0;
    caux=0;
    xi=50;
    yi=0;
    pause=1;
    xb=50;
    yb=101;
    vidas=3;
    tiro=0;
    tiroinimigo1=0;
    tiroinimigo2=0;
    tiroinimigo3=0;
    tiroinimigo4=0;
    tiroboss=0;
    powerup=0;
    maxtiros=3;
    inimigos=0;
    bos=0;
    mb=1;
    acerto=0;
    op_menu=0;
    opcao=1;
    gameover=0;
    quantidadeinimigos1=0;
    quantidadeinimigos2=0;
    quantidadeinimigos3=0;
    quantidadeinimigos4=0;
    pp=0;
    pb=0;
    pi1=0;
    rageon=0;
    quant_rage=0;
    rage=0;
    zerou=0;
}
